version: "3.8"

services:
  ##### DATABASE #####
  postgres:
    image: postgres:13.3-alpine
    container_name: online-exam_postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ##### pgAdmin #####
  pgadmin:
    image: dpage/pgadmin4:5.3
    container_name: online-exam_pgadmin
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgAdmin
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
